In [1]:
from pandas.io.json import json_normalize
import json
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from matplotlib import cm
import matplotlib.cm as cmx
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.ticker import MaxNLocator

In [2]:
pd.read_csv("./files/scheduler_tests/complete_v3.0/merged_file.csv")

,json.crossfold.sampleSize,json.crossfold.splits,json.step.clusters,json.step.k,json.step.s1. agg m,json.step.s1. max m,json.step.s1. peak,json.step.s1. total m,json.step.s1. total peak,json.step.s2. agg m,json.step.s2. max m,json.step.s2. peak,json.step.s2. total m,json.step.s2. total peak
0,0.5,200.0,100,1.0,1.502893,1.502893,1916400.0,1.502893,1916400.0,1.437035,1.437035,1832421.0,1.437035,1832421.0
1,0.6,200.0,100,1.0,1.561720,1.561720,1990639.0,1.561720,1990639.0,1.446182,1.446182,1843369.0,1.446182,1843369.0
2,0.7,200.0,100,1.0,1.364640,1.364640,2002170.0,1.364640,2002170.0,1.340170,1.340170,1966269.0,1.340170,1966269.0
3,0.8,200.0,100,1.0,1.384526,1.384526,1964568.0,1.384526,1964568.0,1.330127,1.330127,1887379.0,1.330127,1887379.0
4,0.9,200.0,100,1.0,1.473336,1.473336,2001099.0,1.473336,2001099.0,1.405389,1.405389,1908812.0,1.405389,1908812.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25195,NaN,NaN,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25196,NaN,NaN,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25197,NaN,NaN,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25198,NaN,NaN,160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25199,NaN,NaN,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN